### ISSUE TITLE
你好，有个问题想请教一下，为什么我输入rgb图像高斯处理之后，并不是彩色图像呢？

### ISSUE THREAD

**Issue by JaChouSSS** [supercaoO/Color-Loss#1]

**Comment by supercaoO** [comment]
@JaChouSSS 你好，方便贴出你的代码么？我对尺寸为[4, 3, 40, 40]的三通道RGB Tensor执行如下的高斯模糊后输出仍为[4, 3, 40, 40]尺寸的三通道RGB Tensor。
代码：
```python
blur_rgb = Blur(3)
img_rgb1 = torch.randn(4, 3, 40, 40)
img_rgb2 = torch.randn(4, 3, 40, 40)
blur_rgb1 = blur_rgb(img_rgb1)
blur_rgb2 = blur_rgb(img_rgb2)
print(blur_rgb1.size())
```
输出：
```shell
torch.Size([4, 3, 40, 40])
```

**Comment by JaChouSSS** [comment]
感谢你的快速回复，刚刚解决了，处理rgb的时候，要三通道分开，最后得到模糊图就还是彩色的，如果不分开，就会是黑白的
`b = im[:,0:1,:,:]
    g = im[:,1:2,:,:]
    r = im[:,2:3,:,:]
    blur_gray = Blur(1)
    b = blur_gray(b)
    g = blur_gray(g)
    r = blur_gray(r)
    im[:,0:1,:,:] = b
    im[:,1:2,:,:] = g
    im[:,2:3,:,:] = r`

**Comment by supercaoO** [comment]
@JaChouSSS 你好，我刚刚更新了仓库代码，拉取最新代码后，现在你可以直接使用以下更简洁的方式：
```python
blur_rgb = Blur(3)
im = blur_rgb(im)
```
来实现你上面说的需要——对RGB图像的每个通道独立地进行高斯模糊。

创建`Blur`对象时可以选择一个输入参数，如果该参数为3，表示用来处理RGB三通道图像，如果该参数是1，表示用来处理灰度单通道图像。
